version: '3.8'
services:
  caddy:
    image: stephaneklein/caddy-auth-portal:2.2.1-alpine
    command: caddy run --watch --config /config/Caddyfile
    volumes:
      - ./html/:/var/lib/html/
      - ./config/:/config/
    ports:
      - 80:80

networks:
  default:
    name: example-caddy-auth-portal-proxy
