version: '3.8'
services:
  caddy:
    image: stephaneklein/caddy-auth-portal:2.2.1-alpine
    command: caddy run --resume --config /etc/caddy/Caddyfile
    volumes:
      - ./html/:/var/lib/html/
      - ./data/:/data/
      - ./config/:/etc/caddy/
    ports:
      - 80:80

networks:
  default:
    name: example-caddy-auth-portal-proxy
